### ISSUE TITLE
P1 Wajib isi metadata di saat upload data

### ISSUE THREAD

**Issue by senoadiw** [geoenvo/geonode#1]
Lihat ilustrasi dari Flow Upload Layers pada file Improvement1_Upload Spatial Data_20150812.pdf

**Comment by mf4dl1** [comment]
# Requirements

Flow data menjadi :
Upload file > Ubah Metadata > Kelola style

Saat upload data spatial dan dokumen, format isian metadata harus diisi dahulu agar tombol upload aktif (tujuannya agar mendapatkan metadata yang lengkap)

![image](https://cloud.githubusercontent.com/assets/4919662/9597950/f3be35a8-50b0-11e5-8899-ead20315e1af.png)

## Approx MD

10 MD.

**Comment by senoadiw** [comment]
Refer to commits with message: NEW UPLOAD FLOW

**Comment by senoadiw** [comment]
Mandatory metadata fields are:
- title
- date created
- source
- abstract
- regions
- language
- data quality statement
- keywords
