### ISSUE TITLE
P1 Approval for Publish data

### ISSUE THREAD

**Issue by senoadiw** [geoenvo/geonode#2]

**Comment by mf4dl1** [comment]
# Requirments

Upload data oleh user akan otomatis mengirimkan email ke admin SKPD untuk diminta approval publish data.

Saat User melakukan upload data, data tidak secara langsung terpublish (hanya bisa dilihat di internal SKPD) selanjutnya data akan di cek dan di **“approve”** oleh Admin SKPD yang lebih berwenang.

## Approx MD

5 MD.

# Progress

(already 50%)

**Comment by mf4dl1** [comment]
* Approx MD*
5 MD.

* Requirments *
Upload data oleh user akan otomatis mengirimkan email ke admin SKPD untuk diminta approval publish data.

Saat User melakukan upload data, data tidak secara langsung terpublish (hanya bisa dilihat di internal SKPD) selanjutnya data akan di cek dan di **“approve”** oleh Admin SKPD yang lebih berwenang.

**Comment by senoadiw** [comment]
Refer to commits with: NEW UPLOAD FLOW

**Comment by senoadiw** [comment]
Notification feature enabled and added however there is a bug from upstream => http://osgeo-org.1560.x6.nabble.com/uploading-layer-and-enable-notifications-td5214225.html

**Comment by senoadiw** [comment]
Bug fix solution: give www-data write permission to /var/www dir

```
sudo chown root:www-data /var/www
sudo chmod g+w /var/www
```

**Comment by senoadiw** [comment]
Sends layer_created notice email to 'Pengelola Basis Data' group managers.

Must set valid email in my_geonode/local_settings.py (gmail example below):

```
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'geonodeemail@gmail.com'
EMAIL_HOST_PASSWORD = 'geonodeemailpassword'
EMAIL_PORT = 587
```
