### ISSUE TITLE
P1 Kategorisasi folder disatukan dengan page pengisian metadata

### ISSUE THREAD

**Issue by senoadiw** [geoenvo/geonode#3]

**Comment by mf4dl1** [comment]
Wait for #1 .

**Comment by mf4dl1** [comment]
# Requirements

Ketegorisasi folder disatukan dengan page pengisian metadata. User cukup mengisi lengkap di kolom metadata maka otomatis foldering untuk pengisian file juga dilakukan

## Mandays

5 MD.

**Comment by senoadiw** [comment]
Refer to commits with: NEW UPLOAD FLOW

**Comment by senoadiw** [comment]
Foldering structure follows this format:

```
{category}/{regions}/{source}/{year}/layers/{layer filename}
```
