### ISSUE TITLE
P1 Tambah field “Sumber data” / “Data source”

### ISSUE THREAD

**Issue by senoadiw** [geoenvo/geonode#4]

**Comment by mf4dl1** [comment]
# Requirements

Tambah field “Sumber data” / “Data source”.
Field ini berisi informasi “sumber data” >> Pemilik data original ;
Contoh : Citra satelit landsat : USGS.

Field menu berupa kolom isian bebas

## MD

2 MD.

Wait for #1 .

**Comment by senoadiw** [comment]
Refer to commits with: NEW UPLOAD FLOW

**Comment by senoadiw** [comment]
Source uses dropdown widget to prevent user from providing bad/unstandard input values if using text field.
