### ISSUE TITLE
P1 Tambah kolom tanggal per pilihan

### ISSUE THREAD

**Issue by senoadiw** [geoenvo/geonode#5]

**Comment by mf4dl1** [comment]
Wait for #1 .

**Comment by mf4dl1** [comment]
# Requirments

Tambah kolom tanggal per pilihan.

Tanggal Pembuatan | dd/mm/yyyy
Tanggal Publikasi | dd/mm/yyyy
Tanggal Revisi | dd/mm/yyyy

![image](https://cloud.githubusercontent.com/assets/4919662/9599422/0d46c988-50be-11e5-9f71-3fe2ba5fec91.png)

## MD

3 MD.

**Comment by senoadiw** [comment]
Refer to commits with: NEW UPLOAD FLOW

**Comment by senoadiw** [comment]
New custom date metadata fields:
- date created
- date published
- date revised
